version: '3.8'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ~/postgresql/data:/var/lib/postgresql/data

  api:
    depends_on:
      - database
    build: ./
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app
