version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb/data/db:/data/db
    restart: unless-stopped

  api:
    depends_on:
      - mongodb
    build: .
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app
